  USE TesteLG
  GO 
  
CREATE TABLE PESSOA(
  CD_PESSOA INT IDENTITY(1,1),
  NM_PESSOA VARCHAR(300),
  NM_SOBRENOME VARCHAR(255),
  NR_CPF VARCHAR(100),
  FL_ATIVO BIT DEFAULT 1 NOT NULL,
  DT_INSERCAO DATETIME DEFAULT GETDATE() NOT NULL
  CONSTRAINT PK_PESSOA PRIMARY KEY CLUSTERED(CD_PESSOA)
)

CREATE TABLE RELACIONAMENTO_PESSOA(
  CD_RELACIONAMENTO_PESSOA INT IDENTITY(1,1),
  CD_PESSOA INT NOT NULL,
  CD_PESSOA_RELACIONAMENTO INT NOT NULL,
  NR_TIPO_RELACIONAMENTO_PESSOA INT NOT NULL,
  DT_INSERCAO DATETIME DEFAULT GETDATE() NOT NULL
  CONSTRAINT PK_RELACIONAMENTO_PESSOA PRIMARY KEY CLUSTERED(CD_RELACIONAMENTO_PESSOA)
)

CREATE TABLE TELEFONE_PESSOA(
	CD_TELEFONE_PESSOA int IDENTITY(1,1) NOT NULL,
	CD_PESSOA int NOT NULL,
	DDD int NOT NULL,
	TELEFONE varchar(15) NOT NULL,
	NR_TIPO_TELEFONE int NOT NULL,
  DT_INSERCAO DATETIME DEFAULT GETDATE() NOT NULL
 CONSTRAINT PK_TELEFONE_PESSOA PRIMARY KEY CLUSTERED (CD_TELEFONE_PESSOA)
)

CREATE TABLE TIPO_TELEFONE(
	NR_TIPO_TELEFONE int IDENTITY(1,1) NOT NULL,
	NM_TIPO_TELEFONE varchar(50) NOT NULL,
  DT_INSERCAO DATETIME DEFAULT GETDATE() NOT NULL
 CONSTRAINT PK_TIPO_TELEFONE PRIMARY KEY CLUSTERED (NR_TIPO_TELEFONE)
)

CREATE TABLE TIPO_RELACIONAMENTO_PESSOA(
	NR_TIPO_RELACIONAMENTO_PESSOA int IDENTITY(1,1) NOT NULL,
	NM_TIPO_RELACIONAMENTO_PESSOA varchar(50) NOT NULL,
  DT_INSERCAO DATETIME DEFAULT GETDATE() NOT NULL
 CONSTRAINT PK_TIPO_RELACIONAMENTO_PESSOA PRIMARY KEY CLUSTERED (NR_TIPO_RELACIONAMENTO_PESSOA)
)


 ALTER TABLE RELACIONAMENTO_PESSOA
	ADD CONSTRAINT FK_RELACIONAMENTO_PESSOA FOREIGN KEY (CD_PESSOA)
	REFERENCES PESSOA (CD_PESSOA)

   ALTER TABLE TELEFONE_PESSOA
	  ADD CONSTRAINT FK_TELEFONE_PESSOA FOREIGN KEY (CD_PESSOA)
	  REFERENCES PESSOA (CD_PESSOA)

  insert into TIPO_RELACIONAMENTO_PESSOA(NM_TIPO_RELACIONAMENTO_PESSOA) values
  ('Pai')
  ,('Mae')
  ,('Irmao')
  ,('Amigo')
  ,('Outros')

    insert into TIPO_TELEFONE(NM_TIPO_TELEFONE) values
  ('Celular')
  ,('Residencial')
  ,('Comercial')

  --truncate table pessoa
  --truncate table RELACIONAMENTO_PESSOA
  --truncate table TELEFONE_PESSOA
  --drop table RELACIONAMENTO_PESSOA

  --ALTER TABLE RELACIONAMENTO_PESSOA DROP CONSTRAINT FK_RELACIONAMENTO_PESSOA
  --ALTER TABLE TELEFONE_PESSOA DROP CONSTRAINT FK_TELEFONE_PESSOA
